# Generated by Django 5.2.4 on 2025-07-22 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_memorygame', '0002_game_attempts_game_status_statistic'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='level',
            field=models.CharField(choices=[('B', 'Básico'), ('M', 'Medio'), ('A', 'Avanzado')], default='B', max_length=1),
        ),
    ]
