# Generated by Django 5.2.4 on 2025-07-22 04:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app_memorygame', '0003_game_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='max_attempts',
            field=models.IntegerField(default=18),
        ),
    ]
